// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vedxpvnmbpzrljwzretv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlZHhwdm5tYnB6cmxqd3pyZXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzA1MzIsImV4cCI6MjA2NTc0NjUzMn0.5lE0o2YqxMd6LbpjnBLFeQMvQsjOCHLRChpJ-vxLWWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);